#job:

 # script:

  #- echo "Oi alunos"

 # - echo "da turma 2"
#build:
 # script:
  #- echo "Oi alunos"

  #- echo "da turma 2"

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "olá"
    - echo "tudo bem?"

test:
  stage: test
  script:
  - echo "bom dia!"
  - echo "boa tarde!"

  