#job:

 # script:

  #- echo "Oi alunos"

 # - echo "da turma 2"
#build:
 # script:
  #- echo "Oi alunos"

  #- echo "da turma 2"
image: maven #imagem maven que foi buscada no site hub.docker

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn package -Dmaven.test.skip

test:
  stage: test
  script:
  - echo "bom dia!"
  - echo "boa tarde!"

  